version: '3'
services:
  api:
    container_name: api
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - .:/app
