services:
   many-tooh:
    container_name: many-tooh
    image: many-tooh-api
    platform: linux/amd64
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "4200:4200"
    environment:
      - PORT=4200
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - TZ=Asia/Bangkok
    networks:
      - my_network
    volumes:
      - .:/app

networks:
  my_network:
    external: true
