name: lint
on:
  push:
    branches: 
      - develop
    paths:
      - '**.go'
  pull_request:
    branches:
      - develop
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          args: --timeout 3m